### ISSUE TITLE
UTF-8 Error

### ISSUE THREAD

**Issue by sanderzdb** [rpbouman/xavier#10]
Hi,

The file xavier/src/messages/messages-de.js still gives an UTF-8 error. The comment on line 167 jumped to line 168.

Sander

**Comment by rpbouman** [comment]
Is this problem still occurring? Could you perhaps send me a pull request?

**Comment by sanderzdb** [comment]
Unfortunately I have left the project and I don't have access anymore to
the environment I was working in at the time.

**Comment by rpbouman** [comment]
Hi Sanderzdb!

hey, that's a pity. Is it possible for you to give the people at your
former project a nudge so they can contact me? I'd be happy to look into it
now that I have a little bit more time.

Best regards,

Roland

On Wed, Mar 9, 2016 at 10:03 AM, sanderzdb notifications@github.com wrote:

> Unfortunately I have left the project and I don't have access anymore to
> the environment I was working in at the time.
> 
> On Wed, Mar 9, 2016 at 12:25 AM, Roland notifications@github.com wrote:
> 
> > Is this problem still occurring? Could you perhaps send me a pull
> > request?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/rpbouman/xavier/issues/10#issuecomment-194017137.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rpbouman/xavier/issues/10#issuecomment-194192266.

## 

Roland Bouman
blog: http://rpbouman.blogspot.com/
twitter: @rolandbouman
linkedin: http://www.linkedin.com/profile/view?id=5142800&trk=tab_pro

Author of "Pentaho Solutions" (Wiley, ISBN: 978-0-470-48432-6
http://tinyurl.com/lvxa88) and "Pentaho Kettle Solutions" (Wiley, ISBN:
978-0-470-63517-9 http://tinyurl.com/33r7a8m)

**Comment by sanderzdb** [comment]
I've send you an email on the address of the oil company we used to work at together :)

**Comment by rpbouman** [comment]
Ah hey - duurde even voordat dat kwartje gevallen was. Dankje!
