### ISSUE TITLE
extending each query type with copyright and informational text at the bottom of the right-hand window

### ISSUE THREAD

**Issue by amateur-hkl** [rpbouman/xavier#14]
But where should the text come from? It does not quite fit with the index.html concept.  
Can it be obtained from the cube or from a cube-related table in the database?

**Comment by rpbouman** [comment]
Hi Hans!

By query type, you mean things like "table", "pivot table", "grouped bar chart" etc? 

These query types are pluggable. It's up to their author to make it behave as intended. If that includes showing a information message or copyright notice, they are free to implement that. 

They should probably solve this in the createDom method. There they can completely control the contents of the tab. Normally they would at least render a query designer and a visualizer. The pivot table adds a toolbar as well. But you're free to add code that shows any information messages.

**Comment by amateur-hkl** [comment]
OK,

I understand. It is then up to the person configuring the Xavier
application to modify the different Tabs with Javascript according to
individual tastes.

Hans Kristian

2016-03-19 12:13 GMT+01:00 Roland notifications@github.com:

**Comment by rpbouman** [comment]
Hi Hans!

"It is then up to the person configuring the Xavier
application to modify the different Tabs with Javascript according to
individual tastes."

well, with the current query types, it's not really a matter of "configuring". None of the query types I built has an option to set such a message.

Perhaps if you could explain a bit more about the use case - it would help me consider whether I should think about adding something like this.

**Comment by amateur-hkl** [comment]
I expect many data providers to require each "page" to show prominently a
Copyright notification, and also one to be included on Excel exports..

In fact, some contacts request that todaqy.

Hans Kristian

2016-03-19 12:59 GMT+01:00 Roland notifications@github.com:

**Comment by rpbouman** [comment]
Hans, thanks! 

Ok, well, if that is the case, then I think it would be best if they would code their query types in such a way that it includes code for rendering such notices. I would be happy to provide advice on how to do that.

**Comment by amateur-hkl** [comment]
Hi rpbouman/xavier,

I'd like to add you to my professional network on LinkedIn.
- Hans Kristian

Confirm that you know Hans Kristian: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=VDM0duPX&invitationId=6194581010546507776&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiuha2bvy%7E7e

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iuha2bvy-7e&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEaDEfPPbJpPAAAAVfeSzxDur03OhFRL3oG3XkiNMkRgBfwGO6bYA-GGo1N_ywpwqsm9C-noGiD_PquKkRLg8vjsCAU99KcSA0oaVj0dvENKzuwLCN9iXOrfvsV0fmsskGvEPYwpnYlLq9JkVoy3uSSnP0TXKhPt978oNc2iSP1gZcGgy5VZBHWF7vsQoSqmr4l&eid=0-iuha2bvy-7e

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iuha2bvy-7e&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by amateur-hkl** [comment]
Hi rpbouman/xavier,

I'd like to add you to my professional network on LinkedIn.
- Hans Kristian

Confirm that you know Hans Kristian: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=uKfJAaB8&invitationId=6194581010491994112&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiuha2kiz%7Ea5

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iuha2kiz-a5&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFlCEE3HyatpgAAAVfeS3uOUFuCryuHZUZqpQxySB_Ha1gBli3PgFhtLw9URndl2mCQNMnDbpQIHdKQYUZXRCoNmwiEPfRnMR8ZhpXtlMyYBeSmV1eAp_BmMuHO3HtKxGvnjanWLWmIwc6CI8D3raHECt5p1ndSsLOKlEYUPAwD2JJOx1YH7qbu8inm6DduvM5o&eid=0-iuha2kiz-a5

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iuha2kiz-a5&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
